# Generated by Django 3.0.8 on 2020-07-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=100)),
                ('organiza', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('premios', models.TextField(blank=True, null=True)),
                ('bolos', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bolos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField(default=0)),
                ('i', models.IntegerField(default=0)),
                ('n', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('o', models.IntegerField(default=0)),
            ],
        ),
    ]
