# Generated by Django 3.0.8 on 2020-07-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField(default=0)),
                ('i', models.IntegerField(default=0)),
                ('n', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('o', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Bolos',
        ),
        migrations.AddField(
            model_name='bingo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bolo',
            name='bingos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.Bingo'),
        ),
    ]
