# Generated by Django 3.0.8 on 2020-07-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_auto_20200709_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
